import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const packageDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const rootDirectory = resolve(packageDirectory, "../..");
const contractPath = resolve(rootDirectory, "packages/contracts/openapi.json");
const outputPath = resolve(packageDirectory, "src/index.ts");

function schemaType(schema) {
  if (schema && typeof schema === "object" && "$ref" in schema) {
    return schema.$ref.split("/").at(-1);
  }

  if (schema && typeof schema === "object" && "const" in schema) {
    return JSON.stringify(schema.const);
  }

  if (schema && typeof schema === "object" && Array.isArray(schema.enum)) {
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (schema?.type === "array") {
    return `Array<${schemaType(schema.items)}>`;
  }

  switch (schema?.type) {
    case "boolean":
      return "boolean";
    case "integer":
    case "number":
      return "number";
    case "object":
      return "Record<string, unknown>";
    case "string":
      return "string";
    default:
      return "unknown";
  }
}

function interfaceSource(name, schema) {
  const required = new Set(schema.required ?? []);
  const properties = Object.entries(schema.properties ?? {}).map(
    ([propertyName, propertySchema]) =>
      `  ${propertyName}${required.has(propertyName) ? "" : "?"}: ${schemaType(propertySchema)};`,
  );

  return [`export interface ${name} {`, ...properties, "}"].join("\n");
}

function assertContract(document) {
  const operation = document.paths?.["/system/health"]?.get;

  if (document.openapi !== "3.1.0") {
    throw new Error("Expected the OpenAPI 3.1 contract.");
  }

  if (operation?.operationId !== "getSystemHealth") {
    throw new Error("Expected GET /system/health to expose getSystemHealth.");
  }

  for (const schemaName of [
    "SystemHealthData",
    "SystemHealthResponse",
    "ProblemDetailsError",
    "ProblemDetails",
  ]) {
    if (!document.components?.schemas?.[schemaName]) {
      throw new Error(`Missing generated client schema: ${schemaName}`);
    }
  }

  return operation;
}

function renderClient(document) {
  const operation = assertContract(document);
  const schemas = document.components.schemas;
  const scopeParameter = operation.parameters?.find((parameter) => parameter.name === "scope");

  const interfaces = Object.entries(schemas).map(([name, schema]) => interfaceSource(name, schema));

  return `/**
 * Generated by packages/generated-api/scripts/generate.mjs.
 * Source: packages/contracts/openapi.json.
 * Do not edit directly.
 */

${interfaces.join("\n\n")}

export interface SystemHealthQuery {
  scope?: ${schemaType(scopeParameter?.schema)};
}

export interface WayfinderClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  readonly problem: ProblemDetails;
  readonly status: number;

  constructor(problem: ProblemDetails) {
    super(problem.detail);
    this.name = "ApiError";
    this.problem = problem;
    this.status = problem.status;
  }
}

function isProblemDetails(value: unknown): value is ProblemDetails {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.detail === "string" &&
    typeof candidate.status === "number" &&
    typeof candidate.title === "string" &&
    typeof candidate.type === "string"
  );
}

function responseBody(value: unknown, status: number): ProblemDetails {
  if (isProblemDetails(value)) {
    return value;
  }

  return {
    detail: \`The API returned an unexpected \${status} response.\`,
    status,
    title: "API request failed",
    type: "https://wayfinder.dev/problems/api-request-failed",
  };
}

export function createWayfinderClient(options: WayfinderClientOptions) {
  const request = options.fetch ?? globalThis.fetch;
  const baseUrl = options.baseUrl.replace(/\\/+$/, "");

  return {
    async getSystemHealth(input: SystemHealthQuery = {}): Promise<SystemHealthResponse> {
      const query = new URLSearchParams();
      if (input.scope) {
        query.set("scope", input.scope);
      }

      const queryString = query.toString();
      const url = \`\${baseUrl}/api/v1/system/health\${queryString ? \`?\${queryString}\` : ""}\`;
      const response = await request(url, {
        headers: {
          accept: "application/json, application/problem+json",
          ...options.headers,
        },
      });
      const payload = JSON.parse(await response.text()) as unknown;

      if (!response.ok) {
        throw new ApiError(responseBody(payload, response.status));
      }

      return payload as SystemHealthResponse;
    },
  };
}
`;
}

const document = JSON.parse(await readFile(contractPath, "utf8"));
const generated = renderClient(document);
const checkOnly = process.argv.includes("--check");

if (checkOnly) {
  const current = await readFile(outputPath, "utf8");

  if (current !== generated) {
    throw new Error(
      "Generated API client is stale. Run `pnpm --filter @personal-finance/generated-api generate`.",
    );
  }

  console.log("Generated API client is up to date.");
} else {
  await writeFile(outputPath, generated);
  console.log(`Generated ${outputPath}`);
}
