#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.local}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages below.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="${ENV_FILE:-.env.local}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [[ ! -f .env.example ]]; then
  warn "Missing .env.example in $REPO_ROOT"
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"
if [[ ! -f "$ENV_FILE" ]]; then
  cp .env.example "$ENV_FILE"
  say "Created $ENV_FILE from .env.example"
fi

ask_default() {
  local key="$1" prompt="$2" default="$3" value
  ask "$key" "$prompt [default: $default]"
  value="${!key:-$default}"
  printf -v "$key" '%s' "$value"
}

write_optional() {
  local key="$1" value="$2"
  if [[ -n "$value" ]]; then
    write_env "$key" "$value"
  fi
}

require_present() {
  local key="$1" value
  value=$(_existing "$key" || true)
  if [[ -n "$value" ]]; then
    say "✓ $key is present (value hidden)"
  else
    warn "$key is missing"
    SKIPPED+=("$key")
  fi
}

stage "Local safety and identifiers"
say "We will establish local-only values before opening any provider dashboard."
step "Use a dedicated development/test account for each provider. Do not use real financial data or production credentials."
step "Choose the Expo scheme and native identifiers that the future app will use; these are configuration values, not secrets."
ask_default APP_BASE_URL "Local web application URL:" "http://localhost:3000"
ask_default API_BASE_URL "Local API URL:" "http://localhost:3000"
ask_default EXPO_SCHEME "Expo custom URL scheme:" "personalfinance"
ask_default EXPO_IOS_BUNDLE_ID "iOS bundle identifier:" "com.personalfinance.app"
ask_default EXPO_ANDROID_PACKAGE "Android package name:" "com.personalfinance.app"
write_env APP_BASE_URL "$APP_BASE_URL"
write_env API_BASE_URL "$API_BASE_URL"
write_env EXPO_SCHEME "$EXPO_SCHEME"
write_env EXPO_IOS_BUNDLE_ID "$EXPO_IOS_BUNDLE_ID"
write_env EXPO_ANDROID_PACKAGE "$EXPO_ANDROID_PACKAGE"

if [[ -n "$(_existing AUTH0_SECRET || true)" ]]; then
  ask_secret AUTH0_SECRET "Auth0 web session secret (Enter keeps the existing value):"
else
  if command -v openssl >/dev/null 2>&1; then
    AUTH0_SECRET="$(openssl rand -hex 32)"
    say "Generated AUTH0_SECRET locally; its value was not displayed."
  else
    ask_secret AUTH0_SECRET "Generate and paste a 64-character hex Auth0 session secret:"
  fi
fi
write_env AUTH0_SECRET "$AUTH0_SECRET"

if [[ -n "$(_existing WORKOS_COOKIE_PASSWORD || true)" ]]; then
  ask_secret WORKOS_COOKIE_PASSWORD "WorkOS cookie password (Enter keeps the existing value):"
else
  if command -v openssl >/dev/null 2>&1; then
    WORKOS_COOKIE_PASSWORD="$(openssl rand -base64 32)"
    say "Generated WORKOS_COOKIE_PASSWORD locally; its value was not displayed."
  else
    ask_secret WORKOS_COOKIE_PASSWORD "Paste a randomly generated WorkOS cookie password (32+ characters):"
  fi
fi
write_env WORKOS_COOKIE_PASSWORD "$WORKOS_COOKIE_PASSWORD"

stage "Auth0 — web, API, and Expo application"
say "Configure only an isolated Auth0 development tenant. The current Next.js SDK uses /auth/* routes, while the native SDK uses a custom-scheme callback."
open_url "https://auth0.com/docs/quickstart/webapp/nextjs"
open_url "https://auth0.com/docs/quickstart/native/react-native-expo"
step "Create or select a development tenant. Create a Regular Web Application for the future Next.js app."
step "Set its local callback URL to http://localhost:3000/auth/callback, logout URL to http://localhost:3000, and allowed web origin to http://localhost:3000."
step "Create a separate Native Application for Expo. Use the scheme and iOS/Android identifiers from stage 1; configure the exact platform callback URLs shown in the Auth0 Expo guide."
step "Create a test API with a unique audience identifier. Use the default below unless you already chose another identifier."
step "Enable email/password and Google. Enable Apple only if the development tenant offers a workable test configuration; record any provider-specific blocker rather than weakening security."
ask AUTH0_DOMAIN "Copy the Auth0 Domain shown in the dashboard (host only, no https:// or trailing slash):"
ask AUTH0_CLIENT_ID "Copy the Regular Web Application Client ID:"
ask_secret AUTH0_CLIENT_SECRET "Copy the Regular Web Application Client Secret:"
ask AUTH0_NATIVE_CLIENT_ID "Copy the Native Application Client ID:"
ask_default AUTH0_AUDIENCE "Auth0 API audience identifier:" "https://api.personal-finance.local"
write_env AUTH0_DOMAIN "$AUTH0_DOMAIN"
write_env AUTH0_CLIENT_ID "$AUTH0_CLIENT_ID"
write_env AUTH0_CLIENT_SECRET "$AUTH0_CLIENT_SECRET"
write_env AUTH0_NATIVE_CLIENT_ID "$AUTH0_NATIVE_CLIENT_ID"
write_env AUTH0_AUDIENCE "$AUTH0_AUDIENCE"
write_env AUTH0_SCOPE "openid profile email offline_access"
write_env AUTH0_WEB_CALLBACK_URL "${APP_BASE_URL%/}/auth/callback"
write_env AUTH0_WEB_LOGOUT_URL "${APP_BASE_URL%/}"
write_env AUTH0_WEB_ALLOWED_ORIGIN "${APP_BASE_URL%/}"
AUTH0_HOST="${AUTH0_DOMAIN#https://}"
AUTH0_HOST="${AUTH0_HOST#http://}"
AUTH0_HOST="${AUTH0_HOST%/}"
write_env AUTH0_NATIVE_DOMAIN "$AUTH0_HOST"
write_env AUTH0_NATIVE_CALLBACK_URL_IOS "${EXPO_SCHEME}://${AUTH0_HOST}/ios/${EXPO_IOS_BUNDLE_ID}/callback"
write_env AUTH0_NATIVE_CALLBACK_URL_ANDROID "${EXPO_SCHEME}://${AUTH0_HOST}/android/${EXPO_ANDROID_PACKAGE}/callback"

stage "Clerk — development instance and native access"
say "Use Clerk's development instance only. Its Native API setting is required for native integration and should not be enabled on a production instance until its bot-protection implications are reviewed."
open_url "https://clerk.com/docs/guides/development/managing-environments"
open_url "https://clerk.com/docs/expo/getting-started/quickstart"
step "Create or select the development application, then open API keys."
step "Enable email/password and Google. Enable Apple only if the dashboard provides a testable configuration; record limitations."
step "In Native applications, enable Native API for this development instance only."
step "Configure localhost as an allowed origin if the dashboard requests it. Do not add wildcard production origins."
ask NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "Copy Clerk's development Publishable Key:"
ask_secret CLERK_SECRET_KEY "Copy Clerk's development Secret Key:"
ask CLERK_JWT_ISSUER_URL "Optional Clerk JWT issuer URL for API validation (press Enter to skip):"
EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY="$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
write_env NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
write_env EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY "$EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY"
write_env CLERK_SECRET_KEY "$CLERK_SECRET_KEY"
write_optional CLERK_JWT_ISSUER_URL "$CLERK_JWT_ISSUER_URL"

stage "WorkOS — staging AuthKit applications"
say "WorkOS separates staging from production. Keep the staging API key server-side; it must never be placed in an Expo public environment variable."
open_url "https://workos.com/docs/authkit/environments"
open_url "https://workos.com/docs/sdks/authkit-nextjs"
open_url "https://workos.com/docs/integrations/react-native-expo"
step "Create or select the WorkOS staging environment. Do not unlock or configure production for this spike."
step "Create a web application and configure the local redirect http://localhost:3000/callback and sign-out URL http://localhost:3000."
step "Create a separate mobile application if the dashboard supports it, but wait for the Expo app to generate its exact redirect URI before registering a production-like callback."
step "Enable email/password and Google. Enable Apple only if the staging environment provides a testable setup; record limitations."
ask WORKOS_CLIENT_ID "Copy the WorkOS staging web Client ID:"
ask WORKOS_MOBILE_CLIENT_ID "Optional WorkOS staging mobile Client ID (press Enter to skip until Expo exists):"
ask_secret WORKOS_API_KEY "Copy the WorkOS staging API key (starts with sk_test_):"
ask_default NEXT_PUBLIC_WORKOS_REDIRECT_URI "WorkOS local web redirect URI:" "${APP_BASE_URL%/}/callback"
ask_default WORKOS_WEB_LOGOUT_URI "WorkOS local sign-out URI:" "${APP_BASE_URL%/}"
ask WORKOS_MOBILE_REDIRECT_URI "Optional exact Expo redirect URI (press Enter if Expo has not generated it yet):"
write_env WORKOS_CLIENT_ID "$WORKOS_CLIENT_ID"
write_optional WORKOS_MOBILE_CLIENT_ID "$WORKOS_MOBILE_CLIENT_ID"
write_env WORKOS_API_KEY "$WORKOS_API_KEY"
write_env NEXT_PUBLIC_WORKOS_REDIRECT_URI "$NEXT_PUBLIC_WORKOS_REDIRECT_URI"
write_env WORKOS_WEB_LOGOUT_URI "$WORKOS_WEB_LOGOUT_URI"
write_optional WORKOS_MOBILE_REDIRECT_URI "$WORKOS_MOBILE_REDIRECT_URI"

stage "Test users, safety checks, and issue hand-off"
say "This stage records only test identities and non-secret setup status. Never record passwords, API keys, private keys, or real financial data."
open_url "https://github.com/ralonsodeniz/personal-finance/issues/16"
step "Create one test owner and one test advisor in each provider, using test email accounts or aliases."
step "Use fake household and investment records only when the prototype has a data store; the current HTML harness remains data-free."
ask AUTH_SPIKE_OWNER_EMAIL "Test owner email (optional; press Enter to skip):"
ask AUTH_SPIKE_ADVISOR_EMAIL "Test advisor email (optional; press Enter to skip):"
ask AUTH_SPIKE_TEST_ORGANIZATION_ID "WorkOS test organization ID, if created (optional; press Enter to skip):"
write_optional AUTH_SPIKE_OWNER_EMAIL "$AUTH_SPIKE_OWNER_EMAIL"
write_optional AUTH_SPIKE_ADVISOR_EMAIL "$AUTH_SPIKE_ADVISOR_EMAIL"
write_optional AUTH_SPIKE_TEST_ORGANIZATION_ID "$AUTH_SPIKE_TEST_ORGANIZATION_ID"
if confirm "Have you used only development/staging providers, test identities, and fake data?"; then
  say "Safety confirmation recorded."
else
  SKIPPED+=("Safety confirmation: use only development/staging providers, test identities, and fake data")
fi

for required_key in \
  APP_BASE_URL API_BASE_URL EXPO_SCHEME EXPO_IOS_BUNDLE_ID EXPO_ANDROID_PACKAGE \
  AUTH0_DOMAIN AUTH0_CLIENT_ID AUTH0_CLIENT_SECRET AUTH0_NATIVE_CLIENT_ID AUTH0_AUDIENCE AUTH0_SECRET \
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY CLERK_SECRET_KEY \
  WORKOS_CLIENT_ID WORKOS_API_KEY WORKOS_COOKIE_PASSWORD NEXT_PUBLIC_WORKOS_REDIRECT_URI; do
  require_present "$required_key"
done

if command -v git >/dev/null 2>&1; then
  if git check-ignore -q "$ENV_FILE"; then
    say "✓ $ENV_FILE is ignored by git."
  else
    warn "$ENV_FILE is not ignored; stop and fix .gitignore before entering more secrets."
    SKIPPED+=("Fix .gitignore before committing or sharing the repository")
  fi
  if git check-ignore -q .env.example; then
    warn ".env.example is unexpectedly ignored; it should remain reviewable as a template."
    SKIPPED+=("Make .env.example visible to git")
  else
    say "✓ .env.example remains visible to git as the safe template."
  fi
fi

finish
